/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class TelaForca1 extends javax.swing.JFrame {
        
        //importações
        Random rd = new Random();
        Scanner tcl = new Scanner(System.in);
        
        //sorteando as palavras
        String  palavras[] = {"PAPEL", "SAPATO", "ZEBRA", "ADESIVO", "LUPA", "TECLADO", "CARRO", "ACENDER", "AFILHADO", "ARDILOSO",
        "ASTERISCO", "CHUVEIRO", "CONTEXTO", "ESFIRRA", "ESQUERDA", "IMPACTO", "POVO", "ANIMADO"};
        int quatidpala = palavras.length;
        int isorte = rd.nextInt(quatidpala);
        String sorte = palavras[isorte];
        String[] casos = new String[palavras.length];
        
        char letra, letram;
        String letracom, utilizadas = "";
        boolean semchance;
        int chance = 6, rodada = 1, vitoria=0;
        String espacos = "";
        
    public TelaForca1() {
        
        initComponents();
        lb_chances.setText(Integer.toString(chance));
        for (int i = 0; i < sorte.length(); i++) {
            casos[i] = " __ ";
        }
        
        for (int j = 0; j < sorte.length(); j++) {
                espacos+=casos[j];
              }
        lb_palavra.setText(espacos);
        
        
        
        lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vazio.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_letra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_forca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_chances = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_utili = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_rodada = new javax.swing.JLabel();
        lb_palavra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_boneco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Não Deixe o Pikachu Morrer!!!!!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_letra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Chute uma Letra");

        bt_forca.setText("Confirmar");
        bt_forca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_forcaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Chances:");

        lb_chances.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_chances.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Letras Chutadas:");

        jl_utili.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_utili.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Rodada:");

        lb_rodada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_rodada.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lb_chances))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lb_rodada)))
                        .addContainerGap(273, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_utili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_letra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_forca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_forca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_letra))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_rodada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_chances))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jl_utili)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        lb_palavra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_palavra.setText("_");
        getContentPane().add(lb_palavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 781, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 381, -1, -1));
        getContentPane().add(lb_boneco, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 290, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_forcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_forcaActionPerformed
       
        String letraNao = tf_letra.getText();
        char letra = letraNao.charAt(0);
        if(chance>=1 && (vitoria != sorte.length())){
        jogo(letra);
        
        } else {
            if(vitoria == sorte.length()) {
            JOptionPane.showMessageDialog(null, "Você ganhou");
            }
            
            if(chance==0){
            JOptionPane.showMessageDialog(null, ("Você perdeu, a palavra era " + sorte));
            
            }
        }
        
        tf_letra.setText("");
       
        
    }//GEN-LAST:event_bt_forcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaForca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaForca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaForca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaForca1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaForca1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_forca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_utili;
    private javax.swing.JLabel lb_boneco;
    private javax.swing.JLabel lb_chances;
    private javax.swing.JLabel lb_palavra;
    private javax.swing.JLabel lb_rodada;
    private javax.swing.JTextField tf_letra;
    // End of variables declaration//GEN-END:variables

public void jogo(char letra){
     vitoria=0;
     semchance = true;
     espacos = "";
        //menu
        lb_rodada.setText(Integer.toString(rodada));
        lb_chances.setText(Integer.toString(chance));
        jl_utili.setText(utilizadas);
        
        letram = Character.toUpperCase(letra);
        utilizadas += " - " + letram;
        
        //checagem de letra
        for (int i = 0; i < sorte.length(); i++) {
            if (letram==sorte.charAt(i)) { 
                letracom = Character.toString(letram);
                casos[i]=letracom;
                semchance = false;
                
            }
        }
        
        
        for (int j = 0; j < sorte.length(); j++) {
                espacos+=casos[j] + " ";
        }
        lb_palavra.setText(espacos);
        
        if (semchance) {
            chance--;
        }
        
        for (int i = 0; i < sorte.length(); i++) {
            if (!(casos[i].equals(" __ "))) {
             vitoria++;
            }
        }
         
        
        lb_rodada.setText(Integer.toString(rodada));
        lb_chances.setText(Integer.toString(chance));
        jl_utili.setText(utilizadas);
        
        rodada++;
        
        boneco(chance);

}

public void boneco(int vida){
    switch(vida){
        case 0:
            System.out.println("0");
            lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bone.png")));
        break;
        
        case 1:
            System.out.println("1");
            lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/perdir.png")));
        break;
        
        case 2:
            System.out.println("2");
            lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/braesq.png")));
        break;
        
        case 3:
            System.out.println("3");
            lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bradir.png")));
        break;
        
        case 4:
            System.out.println("4");
            lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corpo.png")));
        break;
        
        case 5:
            System.out.println("5");
            lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cabeca.png")));
        break;
        
        case 6:
            System.out.println("6");
            lb_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vazio.png")));
        break;
    }
}


}
