/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.Random;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class TelaForca extends javax.swing.JFrame {
        
        //importações
        Random rd = new Random();
        
        
        //sorteando as palavras
        String  palavras[] = {"PAPEL", "SAPATO", "ZEBRA", "ADESIVO", "LUPA", "TECLADO", "CARRO", "ACENDER", "AFILHADO", "ARDILOSO",
        "ASTERISCO", "CHUVEIRO", "CONTEXTO", "ESFIRRA", "ESQUERDA", "IMPACTO", "POVO", "ANIMADO"};
        int quatidpala = palavras.length;
        int isorte = rd.nextInt(quatidpala);
        String sorte = palavras[isorte];
        String[] casos = new String[palavras.length];
        
        char letra, letram;
        String letracom, utilizadas = "";
        boolean semchance;
        int chance = 6, rodada = 1, vitoria=0;
        String espacos = "";
    public TelaForca() {
        
        initComponents();
        lb_chances.setText(Integer.toString(chance));
        for (int i = 0; i < sorte.length(); i++) {
            casos[i] = " __ ";
        }
        
        for (int j = 0; j < sorte.length(); j++) {
                espacos+=casos[j];
              }
        lb_palavra.setText(espacos);
        
        parte(false, false, false, false, false, false, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_letra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_forca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_chances = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_utili = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_rodada = new javax.swing.JLabel();
        lb_palavra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cabeca = new javax.swing.JLabel();
        orelhas = new javax.swing.JLabel();
        corpo2 = new javax.swing.JLabel();
        corpo1 = new javax.swing.JLabel();
        perna1 = new javax.swing.JLabel();
        perna2 = new javax.swing.JLabel();
        braco1 = new javax.swing.JLabel();
        braco2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Não Deixe o Pikachu Morrer!!!!!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_letra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Chute uma Letra");

        bt_forca.setText("Confirmar");
        bt_forca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_forcaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Chances:");

        lb_chances.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_chances.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Letras Chutadas:");

        jl_utili.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_utili.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Rodada:");

        lb_rodada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lb_rodada.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lb_chances))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lb_rodada)))
                        .addContainerGap(273, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_utili, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_letra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_forca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_forca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_letra))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_rodada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_chances))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jl_utili)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        lb_palavra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_palavra.setText("_");
        getContentPane().add(lb_palavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 781, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 381, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("___________");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("___________");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 195, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 13, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 13, 187));

        cabeca.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        cabeca.setForeground(new java.awt.Color(255, 153, 0));
        cabeca.setText("O");
        jPanel2.add(cabeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        orelhas.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        orelhas.setForeground(new java.awt.Color(0, 0, 0));
        orelhas.setText("<O>");
        jPanel2.add(orelhas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 70, -1));

        corpo2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        corpo2.setForeground(new java.awt.Color(255, 153, 0));
        corpo2.setText("|||-");
        jPanel2.add(corpo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        corpo1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        corpo1.setForeground(new java.awt.Color(255, 153, 0));
        corpo1.setText("|||");
        jPanel2.add(corpo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        perna1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        perna1.setForeground(new java.awt.Color(255, 153, 0));
        perna1.setText("/");
        jPanel2.add(perna1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 30, -1));

        perna2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        perna2.setForeground(new java.awt.Color(255, 153, 0));
        perna2.setText("\\");
            jPanel2.add(perna2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 30, -1));

            braco1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
            braco1.setForeground(new java.awt.Color(255, 153, 0));
            braco1.setText("___");
            jPanel2.add(braco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

            braco2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
            braco2.setForeground(new java.awt.Color(255, 153, 0));
            braco2.setText("___");
            jPanel2.add(braco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

            getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 320, 240));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void bt_forcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_forcaActionPerformed
        
        
        String letraNao = tf_letra.getText();
        char letra = letraNao.charAt(0);
        if(chance>=1 && (vitoria != sorte.length())){
        jogo(letra);
        
        } else {
            if(vitoria == sorte.length()) {
            JOptionPane.showMessageDialog(null, "Você ganhou");
            this.dispose();
            }
            
            if(chance==0){
            JOptionPane.showMessageDialog(null, ("Você perdeu, a palavra era " + sorte));
            this.dispose();
            }
        }
        
        tf_letra.setText("");
        
    }//GEN-LAST:event_bt_forcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaForca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaForca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel braco1;
    private javax.swing.JLabel braco2;
    private javax.swing.JButton bt_forca;
    private javax.swing.JLabel cabeca;
    private javax.swing.JLabel corpo1;
    private javax.swing.JLabel corpo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jl_utili;
    private javax.swing.JLabel lb_chances;
    private javax.swing.JLabel lb_palavra;
    private javax.swing.JLabel lb_rodada;
    private javax.swing.JLabel orelhas;
    private javax.swing.JLabel perna1;
    private javax.swing.JLabel perna2;
    private javax.swing.JTextField tf_letra;
    // End of variables declaration//GEN-END:variables

public void jogo(char letra){
     vitoria=0;
     semchance = true;
     espacos = "";
        //menu
        lb_rodada.setText(Integer.toString(rodada));
        lb_chances.setText(Integer.toString(chance));
        jl_utili.setText(utilizadas);
        
        letram = Character.toUpperCase(letra);
        utilizadas += " - " + letram;
        
       
        for (int i = 0; i < sorte.length(); i++) {
            if (letram==sorte.charAt(i)) { 
                letracom = Character.toString(letram);
                casos[i]=letracom;
                semchance = false;
                
            }
        }
        
        
        for (int j = 0; j < sorte.length(); j++) {
                espacos+=casos[j] + " ";
        }
        lb_palavra.setText(espacos);
        
        if (semchance) {
            chance--;
        }
        
        for (int i = 0; i < sorte.length(); i++) {
            if (!(casos[i].equals(" __ "))) {
             vitoria++;
            }
        }
         
        
        lb_rodada.setText(Integer.toString(rodada));
        lb_chances.setText(Integer.toString(chance));
        jl_utili.setText(utilizadas);
        
        rodada++;
        boneco(chance);


}

public void boneco(int vida){
    switch(vida){
        case 0:
            parte(true, true, true, true, true, true, true, true);
        break;
        
        case 1:
            parte(true, true, true, true, true, true, true, false);
        break;
        
        case 2:
            parte(true, true, true, true, true, true, false, false);
        break;
        
        case 3:
            parte(true, true, true, true, true, false, false, false);
        break;
        
        case 4:
            parte(true, true, true, true, false, false, false, false);
        break;
        
        case 5:
            parte(true, true, false, false, false, false, false, false);
        break;
        
        case 6:
            parte(false, false, false, false, false, false, false, false);
        break;
    }
}

public void parte(boolean a, boolean b, boolean c, boolean d, boolean e, boolean f, boolean g, boolean h){
        orelhas.setVisible(a);
        cabeca.setVisible(b);
        corpo1.setVisible(c);
        corpo2.setVisible(d);
        braco1.setVisible(e);
        braco2.setVisible(f);
        perna1.setVisible(g);
        perna2.setVisible(h);
}
}
